name = "deploycontracts"
type = "javascript"
account_id = "7a4e9e411ba05c60c1f17d15f9a34e9e"
workers_dev = true
compatibility_date = "2022-06-14"

[build]
command = "npm run build"
[build.upload]
format = "service-worker"

[env.production]
workers_dev = false
route = "https://workers.deploycontracts.io"
zone_id = "e51170b0c96fef3f98b42a76b8c3064e"
